name: Trigger Jenkins

on:
  push:
    branches:
      - release-13-dev

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins
        run: |
          curl -f -X POST \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            "https://JENKINS_URL/job/plugin-erp-1-dev/build"